USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ARENAFLOW;
CREATE SCHEMA IF NOT EXISTS ARENAFLOW.AI_ML;
CREATE STAGE IF NOT EXISTS ARENAFLOW.AI_ML.SEMANTIC_MODELS;

USE DATABASE arenaflow;
USE SCHEMA arenaflow.ai_ml;


-- CREATE WAREHOUSE COMPUTE 
CREATE WAREHOUSE IF NOT EXISTS WH_ARENAFLOW_HOLS
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

    
-- CREATE COMPUTE POOLS
CREATE COMPUTE POOL IF NOT EXISTS gpu_arenaflow_m
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = GPU_NV_M
;
    

-- External access for pypi integration
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE NETWORK RULE ARENAFLOW.AI_ML.PYPI_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('pypi.org', 'pypi.python.org', 'pythonhosted.org',  'files.pythonhosted.org');

    
CREATE ROLE IF NOT EXISTS ARENAFLOW_ADMIN;
GRANT ROLE ARENAFLOW_ADMIN TO USER mcostner;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ARENAFLOW_ADMIN;


USE ROLE ARENAFLOW_ADMIN;
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION PYPI_ACCESS_INTEGRATION
    ALLOWED_NETWORK_RULES = (PYPI_NETWORK_RULE)
    ENABLED = true;


------------------------------------------------
-- GRANT OWNERSHIP OF COMPUTE TO ARENAFLOW_ADMIN
------------------------------------------------
GRANT OWNERSHIP ON WAREHOUSE WH_ARENAFLOW_HOLS TO ROLE ARENAFLOW_ADMIN;
GRANT OWNERSHIP ON COMPUTE POOL CP_ARENAFLOW_HOLS TO ROLE ARENAFLOW_ADMIN;
GRANT OWNERSHIP ON COMPUTE POOL gpu_arenaflow_m TO ROLE ARENAFLOW_ADMIN;
GRANT OWNERSHIP ON DATABASE ARENAFLOW TO ROLE ARENAFLOW_ADMIN;
GRANT OWNERSHIP ON SCHEMA ARENAFLOW.AI_ML TO ROLE ARENAFLOW_ADMIN;

------------------------------------------------
-- USE NEW ROLE TO CREATE TAG AND CONTACT OBJECTS
------------------------------------------------
USE ROLE ARENAFLOW_ADMIN;

------------------------------------------------
-- CREATE STORAGE FOR OBJECTS
------------------------------------------------
-- CREATE DATABASE IF NOT EXISTS ARENAFLOW;
-- CREATE SCHEMA IF NOT EXISTS ARENAFLOW.AI_ML;

-- CREATE TAG OBJECT
CREATE TAG IF NOT EXISTS ARENAFLOW_TAG;

-- CREATE CONTACT OBJECT
CREATE CONTACT IF NOT EXISTS ARENAFLOW_ADMINS
    EMAIL_DISTRIBUTION_LIST = 'af.users@arenaflow.com'
    URL = ''
    COMMENT = 'SMEs for this table.';


------------------------------------------------
-- TASK GRANT FOR CONTINUOUS PIPELINE
------------------------------------------------
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ARENAFLOW_ADMIN;


------------------------------------------------
-- ADD CONTACTS TO
------------------------------------------------
ALTER DATABASE ARENAFLOW SET CONTACT STEWARD = ARENAFLOW_ADMINS;
ALTER DATABASE ARENAFLOW SET CONTACT SUPPORT = ARENAFLOW_ADMINS;
ALTER DATABASE ARENAFLOW SET CONTACT ACCESS_APPROVAL = ARENAFLOW_ADMINS;

------------------------------------------------
-- ADD TAGS TO
------------------------------------------------

-- DATABASE
ALTER DATABASE ARENAFLOW SET TAG ARENAFLOW_TAG = 'ARENAFLOW_AI';
ALTER WAREHOUSE WH_ARENAFLOW_HOLS SET TAG ARENAFLOW_TAG = 'ARENAFLOW_AI';
ALTER COMPUTE POOL CP_ARENAFLOW_HOLS SET TAG ARENAFLOW_TAG = 'ARENAFLOW_AI';
